/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/components/VApp')['VApp']
    VCard: typeof import('vuetify/components/VCard')['VCard']
    VCol: typeof import('vuetify/components/VGrid')['VCol']
    VContainer: typeof import('vuetify/components/VGrid')['VContainer']
    VFooter: typeof import('vuetify/components/VFooter')['VFooter']
    VIcon: typeof import('vuetify/components/VIcon')['VIcon']
    VImg: typeof import('vuetify/components/VImg')['VImg']
    VKbd: typeof import('vuetify/components/VKbd')['VKbd']
    VMain: typeof import('vuetify/components/VMain')['VMain']
    VOverlay: typeof import('vuetify/components/VOverlay')['VOverlay']
    VResponsive: typeof import('vuetify/components/VResponsive')['VResponsive']
    VRow: typeof import('vuetify/components/VGrid')['VRow']
  }
}
